default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["DB_HOST"] || "db" %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] || "taski_development" %>

test:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] || "taski_test" %>

production:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] || "taski_production" %>
